# Generated by Django 5.2.5 on 2025-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='firma', max_length=50)),
                ('contactname', models.CharField(default='firma', max_length=50)),
                ('address', models.CharField(default='firma', max_length=50)),
                ('phone', models.CharField(default='firma', max_length=50)),
                ('email', models.CharField(default='firma', max_length=50)),
                ('country', models.CharField(default='firma', max_length=50)),
            ],
        ),
    ]
